### ISSUE TITLE
Unable to compile ppKMHD on Ubuntu 20.04

### ISSUE THREAD

**Issue by Yaojie-Yu** [pkestene/ppkMHD#1]
Hi, pkestene. I am trying to install ppKMHD on a Ubuntu 20.04 sever, but I got compile errors. Here was the installation process:
1. Clone the repo and update the submodule
`git clone https://github.com/pkestene/ppkMHD.git `
`git submodule init`
`git submodule update`
2. Build without MPI / With Kokkos-openmp
-  create a build dir
`mkdir build & cd build`
-  cmake command
`cmake -DUSE_MPI=OFF -DKokkos_ENABLE_OPENMP=ON -DKokkos_ENABLE_HWLOC=ON -DUSE_SDM=ON ../`
The cmake output messages are:
> -- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found MPI_C: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Could NOT find PAPI (missing: PAPI_LIBRARY PAPI_INCLUDE_DIR) 
-- Setting default Kokkos CXX standard to 11
-- The project name is: Kokkos
-- Using -std=c++11 for C++11 standard as feature
-- Execution Spaces:
--     Device Parallel: NONE
--     Host Parallel: OPENMP
--       Host Serial: NONE
-- 
-- Architectures:
-- Found TPLHWLOC: /usr/lib/x86_64-linux-gnu/libhwloc.so  
-- Found TPLLIBDL: /usr/lib/x86_64-linux-gnu/libdl.so  
-- Found OpenMP_C: -fopenmp (found version "4.0") 
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Found OpenMP: TRUE (found version "4.0")  
//===================================================
  ppkMHD build configuration:
//===================================================
  C++ Compiler : GNU 5.5.0 
    /usr/bin/c++
  MPI not enabled
  Kokkos OpenMP enabled : ON
  Kokkos CUDA   enabled : OFF
  Kokkos HWLOC  enabled : ON
SDM      enabled : ON
MOOD     enabled : OFF
DOUBLE precision : ON
HWLOC    enabled : ON
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yjy/Documents/ppkMHD/build

- build
`make -j4`
but I get compile errors, the massages are :
>  build git:(master) ✗ make -j4 2> errors.log
Scanning dependencies of target config
Scanning dependencies of target kokkoscore
Scanning dependencies of target monitoring
[  1%] Building CXX object src/utils/config/CMakeFiles/config.dir/inih/ini.cpp.o
[  2%] Building CXX object src/utils/config/CMakeFiles/config.dir/ConfigMap.cpp.o
[  3%] Building CXX object src/utils/monitoring/CMakeFiles/monitoring.dir/OpenMPTimer.cpp.o
[  4%] Building CXX object external/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_CPUDiscovery.cpp.o
[  6%] Building CXX object src/utils/monitoring/CMakeFiles/monitoring.dir/SimpleTimer.cpp.o
[  7%] Building CXX object src/utils/config/CMakeFiles/config.dir/inih/INIReader.cpp.o
[  8%] Building CXX object external/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.o
[  9%] Building CXX object external/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Error.cpp.o
[ 10%] Linking CXX static library libmonitoring.a
[ 10%] Built target monitoring
[ 12%] Building CXX object external/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_ExecPolicy.cpp.o
[ 13%] Linking CXX static library libconfig.a
[ 14%] Building CXX object external/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_HostBarrier.cpp.o
[ 14%] Built target config
Scanning dependencies of target ConfigMapTest
[ 15%] Building CXX object test/configMap/CMakeFiles/ConfigMapTest.dir/ConfigMapTest.cpp.o
[ 16%] Building CXX object external/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_HostSpace.cpp.o
[ 18%] Linking CXX executable ConfigMapTest
[ 19%] Building CXX object external/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_HostSpace_deepcopy.cpp.o
[ 20%] Building CXX object external/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_HostThreadTeam.cpp.o
[ 21%] Building CXX object external/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_MemoryPool.cpp.o
[ 21%] Built target ConfigMapTest
[ 22%] Building CXX object external/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_MemorySpace.cpp.o
[ 24%] Building CXX object external/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Profiling.cpp.o
[ 25%] Building CXX object external/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Serial_Task.cpp.o
[ 26%] Building CXX object external/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_SharedAlloc.cpp.o
[ 27%] Building CXX object external/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Spinwait.cpp.o
[ 28%] Building CXX object external/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Stacktrace.cpp.o
[ 30%] Building CXX object external/kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_hwloc.cpp.o
[ 31%] Building CXX object external/kokkos/core/src/CMakeFiles/kokkoscore.dir/OpenMP/Kokkos_OpenMP_Exec.cpp.o
[ 32%] Building CXX object external/kokkos/core/src/CMakeFiles/kokkoscore.dir/OpenMP/Kokkos_OpenMP_Task.cpp.o
[ 33%] Linking CXX static library libkokkoscore.a
[ 33%] Built target kokkoscore
Scanning dependencies of target kokkoscontainers
[ 34%] Building CXX object external/kokkos/containers/src/CMakeFiles/kokkoscontainers.dir/impl/Kokkos_UnorderedMap_impl.cpp.o
[ 36%] Linking CXX static library libkokkoscontainers.a
[ 36%] Built target kokkoscontainers
Scanning dependencies of target test_euler_eigen_decomposition
Scanning dependencies of target query_device_kokkos
Scanning dependencies of target shared
Scanning dependencies of target test_sdm_lagrange_flux2sol_derivative_interpolation
[ 37%] Building CXX object test/kokkos/CMakeFiles/query_device_kokkos.dir/query_device_kokkos.cpp.o
[ 38%] Building CXX object test/sdm/CMakeFiles/test_sdm_lagrange_flux2sol_derivative_interpolation.dir/test_sdm_lagrange_flux2sol_derivative_interpolation.cpp.o
[ 39%] Building CXX object test/shared/CMakeFiles/test_euler_eigen_decomposition.dir/test_euler_eigen_decomposition.cpp.o
[ 40%] Building CXX object src/shared/CMakeFiles/shared.dir/HydroParams.cpp.o
[ 42%] Linking CXX executable query_device_kokkos
[ 42%] Built target query_device_kokkos
[ 43%] Building CXX object src/shared/CMakeFiles/shared.dir/SolverBase.cpp.o
Scanning dependencies of target muscl
[ 44%] Building CXX object src/muscl/CMakeFiles/muscl.dir/SolverHydroMuscl.cpp.o
[ 45%] Linking CXX executable test_euler_eigen_decomposition
[ 45%] Built target test_euler_eigen_decomposition
[ 46%] Building CXX object src/shared/CMakeFiles/shared.dir/utils.cpp.o
Scanning dependencies of target solver_factory
[ 48%] Building CXX object src/shared/CMakeFiles/solver_factory.dir/SolverFactory.cpp.o
[ 49%] Linking CXX executable test_sdm_lagrange_flux2sol_derivative_interpolation
[ 49%] Built target test_sdm_lagrange_flux2sol_derivative_interpolation
Scanning dependencies of target test_sdm_geom
[ 50%] Building CXX object test/sdm/CMakeFiles/test_sdm_geom.dir/test_sdm_geom.cpp.o
[ 51%] Linking CXX static library libshared.a
[ 51%] Built target shared
Scanning dependencies of target test_sdm_lagrange_sol2sol_derivative
[ 53%] Building CXX object test/sdm/CMakeFiles/test_sdm_lagrange_sol2sol_derivative.dir/test_sdm_lagrange_sol2sol_derivative.cpp.o
[ 54%] Linking CXX executable test_sdm_geom
[ 54%] Built target test_sdm_geom
Scanning dependencies of target test_sdm_lagrange_sol2flux
[ 55%] Building CXX object test/sdm/CMakeFiles/test_sdm_lagrange_sol2flux.dir/test_sdm_lagrange_sol2flux.cpp.o
[ 56%] Linking CXX executable test_sdm_lagrange_sol2sol_derivative
[ 56%] Built target test_sdm_lagrange_sol2sol_derivative
Scanning dependencies of target test_sdm_chebyshev_quadrature
[ 57%] Building CXX object test/sdm/CMakeFiles/test_sdm_chebyshev_quadrature.dir/test_sdm_chebyshev_quadrature.cpp.o
[ 59%] Building CXX object src/muscl/CMakeFiles/muscl.dir/SolverMHDMuscl.cpp.o
[ 60%] Linking CXX executable test_sdm_chebyshev_quadrature
[ 60%] Built target test_sdm_chebyshev_quadrature
Scanning dependencies of target io
[ 61%] Linking CXX executable test_sdm_lagrange_sol2flux
[ 62%] Building CXX object src/utils/io/CMakeFiles/io.dir/IO_common.cpp.o
[ 62%] Built target test_sdm_lagrange_sol2flux
[ 63%] Building CXX object src/utils/io/CMakeFiles/io.dir/IO_ReadWrite.cpp.o
[ 65%] Building CXX object src/utils/io/CMakeFiles/io.dir/IO_VTK.cpp.o
[ 66%] Building CXX object src/utils/io/CMakeFiles/io.dir/IO_ReadWrite_SDM.cpp.o
[ 67%] Linking CXX static library libmuscl.a
[ 67%] Built target muscl
[ 68%] Building CXX object src/utils/io/CMakeFiles/io.dir/IO_VTK_SDM_shared.cpp.o
src/utils/io/CMakeFiles/io.dir/build.make:134: recipe for target 'src/utils/io/CMakeFiles/io.dir/IO_ReadWrite_SDM.cpp.o' failed
CMakeFiles/Makefile2:2303: recipe for target 'src/utils/io/CMakeFiles/io.dir/all' failed
^Csrc/shared/CMakeFiles/solver_factory.dir/build.make:62: recipe for target 'src/shared/CMakeFiles/solver_factory.dir/SolverFactory.cpp.o' failed
CMakeFiles/Makefile2:2361: recipe for target 'src/shared/CMakeFiles/solver_factory.dir/all' failed
Makefile:140: recipe for target 'all' failed

The following .log file gives a detailed message:
[error.log](https://github.com/pkestene/ppkMHD/files/5825634/error.log)

The compiler I used is g++-5.5. Actually, I had tested g++-6, g++-8.1, but they all failed to work. I think the problems are in the VTK write classes. 

Thanks.

**Comment by pkestene** [comment]
Hi @Y-J-Y 

Sorry for the trouble of building ppkMHD.

I'm also using Ubuntu 20.04 with 4 different versions of the gnu compiler: 
- g++-7.5.0
- g++-8.4.0
- g++-9.3.0
- g++-10.2.0
They all build fine on my desktop.

Nevertheless, I cross-checked file `src/utils/io/IO_ReadWrite_SDM.cpp` and there was indeed a missing header. I modified it with commit 4c54fbed222c118
Please update your repo, and check again.

I hope this will solve your build problem. Let me know, if there is still difficulties left.

**Comment by Yaojie-Yu** [comment]
Hi @pkestene 
It works now. Thanks for your help.
